### ISSUE TITLE
Create challenge review rubric

### ISSUE THREAD

**Issue by silvabox** [makersacademy/chitter-challenge#170]

**Comment by tansaku** [comment]
in progress here: https://github.com/makersacademy/course-design/blob/master/challenge-feedback/chitter-challenge/feedback.md

**Comment by tansaku** [comment]
can't seem to attach the pull request: https://github.com/makersacademy/chitter-challenge/pull/174

**Comment by tansaku** [comment]
another related pull request that I can't seem to attach https://github.com/makersacademy/course/pull/450

**Comment by tansaku** [comment]
a separate section for more opinion based stuff?
