### ISSUE TITLE
Travis errors when Ruby version other than 2.2.1 is specified in the Gemfile.

### ISSUE THREAD

**Issue by ptolemybarnes** [makersacademy/chitter-challenge#98]
So, for example, this build fails: https://travis-ci.org/makersacademy/chitter-challenge/builds/69700759

I would like to find a way to have travis support multiple versions of Ruby.

The answer is likely to be here: http://docs.travis-ci.com/user/customizing-the-build/

**Comment by ptolemybarnes** [comment]
Removed Cucumber from rps-challenge: https://github.com/makersacademy/rps-challenge/pull/101

**Comment by ptolemybarnes** [comment]
It's possible to specify multiple ruby versions with travis but it seems like you can't give a range. It would be nice to say "use the Ruby version given in the Gemfile". I don't know if that's possible.

**Comment by spike01** [comment]
https://github.com/travis-ci/travis-ci/issues/953 - see the stuff about build matrixes (probably the good idea), or `sed` (probably not a good idea)
